# Generated by Django 3.1.2 on 2020-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_owner',
            field=models.CharField(default='lol', max_length=100, verbose_name='OWNER'),
            preserve_default=False,
        ),
    ]
