# Generated by Django 3.1.2 on 2020-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_order_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/api/qr_codes/'),
        ),
    ]
