# Generated by Django 3.1.2 on 2020-11-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201114_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
