# Generated by Django 3.1.2 on 2020-11-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_delete_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервера'},
        ),
    ]
