# Generated by Django 3.1.2 on 2020-11-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201114_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Время заказа')),
                ('qrId', models.CharField(max_length=64, verbose_name='QR id')),
                ('nickname', models.CharField(max_length=64, verbose_name='Ник покупателя')),
                ('price', models.IntegerField(verbose_name='Цена продукта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
