# Generated by Django 3.1.2 on 2020-11-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_order_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qrId',
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='', verbose_name='QR slow'),
        ),
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL'),
        ),
    ]
